"""Derive a golden book's reference text from a publisher's EPUB.

For books with no Gutenberg transcription: a retail EPUB of the same printing, or
an omnibus holding the scanned book as one part. The manifest names the content
files to read, in order. Headings are `h1`–`h6`, or paragraphs whose class
starts with one of the manifest's heading prefixes; consecutive headings form one
("Eerste episode 1945" above "1"). Empty paragraphs (blank lines) are left out.
"""

import hashlib
import re
import xml.etree.ElementTree as ET
import zipfile
from html.entities import name2codepoint
from pathlib import Path

from roboscriptorium.golden.gutenberg import Section, _chapter_xhtml, _clean

XHTML = "{http://www.w3.org/1999/xhtml}"
HEADING_TAGS = {f"{XHTML}h{n}" for n in range(1, 7)}


_XML_ENTITIES = {"amp", "lt", "gt", "quot", "apos"}


def _parse(raw: bytes) -> ET.Element:
    """Parse XHTML that uses HTML's named entities (`&nbsp;`), which XML doesn't define."""

    def numeric(m: re.Match) -> str:
        name = m.group(1)
        if name in _XML_ENTITIES or name not in name2codepoint:
            return m.group(0)
        return f"&#{name2codepoint[name]};"

    return ET.fromstring(re.sub(r"&(\w+);", numeric, raw.decode("utf-8")))


def _member(z: zipfile.ZipFile, name: str) -> str:
    matches = [n for n in z.namelist() if n == name or n.endswith("/" + name)]
    if len(matches) != 1:
        raise ValueError(f"{name!r} matches {len(matches)} files in the EPUB")
    return matches[0]


def _is_heading(el: ET.Element, prefixes: tuple[str, ...]) -> bool:
    if el.tag in HEADING_TAGS:
        return True
    classes = (el.get("class") or "").split()
    return el.tag == f"{XHTML}p" and any(c.startswith(prefixes) for c in classes)


def read(epub: Path, files: list[str], heading_prefixes: tuple[str, ...] = ()) -> list[Section]:
    sections: list[Section] = []
    with zipfile.ZipFile(epub) as z:
        for name in files:
            body = _parse(z.read(_member(z, name))).find(f"{XHTML}body")
            for el in body.iter():
                if el.tag not in HEADING_TAGS and el.tag != f"{XHTML}p":
                    continue
                text = _clean(" ".join(el.itertext()).replace(" ", " "))
                if not text:
                    continue
                if _is_heading(el, heading_prefixes):
                    last = sections[-1] if sections else None
                    if last is not None and not last.paragraphs:
                        last.full_heading += f" {text}"
                    else:
                        sections.append(Section(text, text))
                elif sections:
                    sections[-1].paragraphs.append(text)
    return sections


def write_reference(
    epub: Path, source: str, files: list[str], heading_prefixes: tuple[str, ...], out: Path
) -> list[Section]:
    sections = read(epub, files, heading_prefixes)
    text_dir = out / "text"
    text_dir.mkdir(parents=True, exist_ok=True)
    for old in text_dir.glob("chapter-*.xhtml"):
        old.unlink()
    for i, section in enumerate(sections, 1):
        (text_dir / f"chapter-{i}.xhtml").write_text(_chapter_xhtml(section))

    digest = hashlib.sha256(epub.read_bytes()).hexdigest()
    (out / "PROVENANCE.md").write_text(f"""\
# Provenance

Generated by `roboscriptorium golden derive`; don't edit by hand.

- Source: {source}
- EPUB sha256: `{digest}`
- Files: {", ".join(files)}
- {len(sections)} chapters, {sum(len(s.paragraphs) for s in sections)} paragraphs
- Left out: blank lines, everything outside the listed files.
""")
    return sections
